# name: Fake CI Pipeline
# on:
#   push:
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Building..."
#       - run: sleep 10
#       - run: echo "Build done"

#   test:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - run: echo "Running tests..."
#       - run: sleep 15
#       - run: echo "Tests passed"
